-- TODO: お題のクエリを書く。
-- sqlc は「フラットな行」を返すので、入れ子(User→Posts→Comments)は
-- 取得後に Go 側で自分で組み立てることになる。その手間も体感ポイント。
--
-- 例(JOIN1段ぶんの雛形 / 完成させる):
-- name: GetUserWithPosts :many
-- SELECT u.id, u.name, p.id AS post_id, p.title
-- FROM users u
-- LEFT JOIN posts p ON p.user_id = u.id AND p.deleted_at IS NULL
-- WHERE u.id = $1 AND u.deleted_at IS NULL;
--
-- TODO: comments まで JOIN を伸ばし、Go 側で入れ子に詰め直す関数も書いてみる。
