-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "email" character varying NOT NULL, "bio" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "body" text NOT NULL, "published" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "user_posts" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "posts_users_posts" FOREIGN KEY ("user_posts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "comments" table
CREATE TABLE "comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "body" text NOT NULL, "created_at" timestamptz NOT NULL, "post_comments" bigint NOT NULL, "user_comments" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_posts_comments" FOREIGN KEY ("post_comments") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_comments") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create "tags" table
CREATE TABLE "tags" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "post_tags" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "tags_posts_tags" FOREIGN KEY ("post_tags") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");
